-- Elemental Pacman v6.0 username multiplayer foundation
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- The browser asks for account name + password only.
-- Supabase Auth still stores an internal email-shaped identifier generated by the app.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1. Permanent player profiles
-- Passwords stay inside Supabase Auth. Never store passwords in this table.
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  account_name text unique not null
    check (account_name ~ '^[a-z0-9_]{3,20}$'),
  display_name text not null
    check (char_length(display_name) between 3 and 20),
  avatar_key text not null default 'gold',
  total_score integer not null default 0 check (total_score >= 0),
  games_played integer not null default 0 check (games_played >= 0),
  games_won integer not null default 0 check (games_won >= 0),
  pellets_collected integer not null default 0 check (pellets_collected >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_account_name text;
begin
  v_account_name := lower(trim(coalesce(
    new.raw_user_meta_data ->> 'account_name',
    new.raw_user_meta_data ->> 'display_name',
    ''
  )));

  if v_account_name !~ '^[a-z0-9_]{3,20}$' then
    raise exception 'Account name must contain 3 to 20 lowercase letters, numbers, or underscores.';
  end if;

  insert into public.profiles (
    id,
    account_name,
    display_name
  )
  values (
    new.id,
    v_account_name,
    v_account_name
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 2. Multiplayer rooms
-- The creator is the first player and initial host.
-- Players may join while status is waiting OR playing.
-- ---------------------------------------------------------------------------
create table if not exists public.game_rooms (
  id uuid primary key default gen_random_uuid(),
  code text unique not null check (code ~ '^[A-Z0-9]{6}$'),
  host_user_id uuid references public.profiles(id) on delete set null,
  status text not null default 'waiting'
    check (status in ('waiting', 'playing', 'ended')),
  map_seed bigint not null,
  max_players smallint not null default 4
    check (max_players between 2 and 4),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz
);

create table if not exists public.room_players (
  room_id uuid not null references public.game_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  player_slot smallint not null check (player_slot between 1 and 4),
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (room_id, user_id),
  unique (room_id, player_slot)
);

create index if not exists room_players_user_id_idx
  on public.room_players(user_id);

create index if not exists room_players_room_last_seen_idx
  on public.room_players(room_id, last_seen_at);

alter table public.game_rooms enable row level security;
alter table public.room_players enable row level security;

-- Authenticated players may read lobby information.
-- All room writes go through the secured RPC functions below.
drop policy if exists "Authenticated players can read profiles" on public.profiles;
create policy "Authenticated players can read profiles"
on public.profiles
for select
to authenticated
using (true);

drop policy if exists "Players can update their own profile" on public.profiles;
create policy "Players can update their own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Authenticated players can read rooms" on public.game_rooms;
create policy "Authenticated players can read rooms"
on public.game_rooms
for select
to authenticated
using (true);

drop policy if exists "Authenticated players can read room members" on public.room_players;
create policy "Authenticated players can read room members"
on public.room_players
for select
to authenticated
using (true);

revoke update on table public.profiles from authenticated;
grant update (display_name, avatar_key) on table public.profiles to authenticated;
grant select on table public.profiles to authenticated;
grant select on table public.game_rooms to authenticated;
grant select on table public.room_players to authenticated;

-- ---------------------------------------------------------------------------
-- 3. Internal room reconciliation
-- A player sends a heartbeat every 8 seconds.
-- Members silent for more than 30 seconds are removed.
-- The earliest remaining member becomes host.
-- If nobody remains, the room ends.
-- ---------------------------------------------------------------------------
create or replace function public.reconcile_game_room_state(
  p_room_id uuid,
  p_stale_seconds integer default 30
)
returns public.game_rooms
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_room public.game_rooms;
  v_next_host uuid;
begin
  select *
  into v_room
  from public.game_rooms
  where id = p_room_id
  for update;

  if not found then
    return null;
  end if;

  delete from public.room_players
  where room_id = p_room_id
    and last_seen_at < now() - make_interval(secs => greatest(p_stale_seconds, 10));

  select user_id
  into v_next_host
  from public.room_players
  where room_id = p_room_id
  order by joined_at asc, player_slot asc
  limit 1;

  if v_next_host is null then
    update public.game_rooms
    set host_user_id = null,
        status = 'ended',
        ended_at = coalesce(ended_at, now())
    where id = p_room_id;
  elsif v_room.host_user_id is null
     or not exists (
       select 1
       from public.room_players
       where room_id = p_room_id
         and user_id = v_room.host_user_id
     ) then
    update public.game_rooms
    set host_user_id = v_next_host
    where id = p_room_id;
  end if;

  select *
  into v_room
  from public.game_rooms
  where id = p_room_id;

  return v_room;
end;
$$;

-- ---------------------------------------------------------------------------
-- 4. Atomic room functions
-- ---------------------------------------------------------------------------
create or replace function public.create_game_room(
  p_code text,
  p_map_seed bigint
)
returns public.game_rooms
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_room public.game_rooms;
begin
  if v_user_id is null then
    raise exception 'You must be logged in to create a room.';
  end if;

  p_code := upper(trim(p_code));
  if p_code !~ '^[A-Z0-9]{6}$' then
    raise exception 'Room code must contain six letters or numbers.';
  end if;

  insert into public.game_rooms (
    code,
    host_user_id,
    map_seed
  )
  values (
    p_code,
    v_user_id,
    p_map_seed
  )
  returning * into v_room;

  insert into public.room_players (
    room_id,
    user_id,
    player_slot,
    last_seen_at
  )
  values (
    v_room.id,
    v_user_id,
    1,
    now()
  );

  return v_room;
end;
$$;

create or replace function public.join_game_room(p_code text)
returns public.game_rooms
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_room public.game_rooms;
  v_slot smallint;
begin
  if v_user_id is null then
    raise exception 'You must be logged in to join a room.';
  end if;

  p_code := upper(trim(p_code));

  select *
  into v_room
  from public.game_rooms
  where code = p_code
  for update;

  if not found then
    raise exception 'Room % was not found.', p_code;
  end if;

  v_room := public.reconcile_game_room_state(v_room.id, 30);

  if v_room.status = 'ended' then
    raise exception 'This game has ended.';
  end if;

  if exists (
    select 1
    from public.room_players
    where room_id = v_room.id
      and user_id = v_user_id
  ) then
    update public.room_players
    set last_seen_at = now()
    where room_id = v_room.id
      and user_id = v_user_id;

    return v_room;
  end if;

  select candidate.slot
  into v_slot
  from generate_series(1, v_room.max_players) as candidate(slot)
  where not exists (
    select 1
    from public.room_players rp
    where rp.room_id = v_room.id
      and rp.player_slot = candidate.slot
  )
  order by candidate.slot
  limit 1;

  if v_slot is null then
    raise exception 'This room is full.';
  end if;

  insert into public.room_players (
    room_id,
    user_id,
    player_slot,
    last_seen_at
  )
  values (
    v_room.id,
    v_user_id,
    v_slot,
    now()
  );

  if v_room.host_user_id is null then
    update public.game_rooms
    set host_user_id = v_user_id
    where id = v_room.id
    returning * into v_room;
  end if;

  return v_room;
end;
$$;

create or replace function public.leave_game_room(p_room_id uuid)
returns public.game_rooms
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_room public.game_rooms;
  v_next_host uuid;
begin
  if v_user_id is null then
    raise exception 'You must be logged in.';
  end if;

  select *
  into v_room
  from public.game_rooms
  where id = p_room_id
  for update;

  if not found then
    return null;
  end if;

  delete from public.room_players
  where room_id = p_room_id
    and user_id = v_user_id;

  select user_id
  into v_next_host
  from public.room_players
  where room_id = p_room_id
  order by joined_at asc, player_slot asc
  limit 1;

  if v_next_host is null then
    update public.game_rooms
    set host_user_id = null,
        status = 'ended',
        ended_at = coalesce(ended_at, now())
    where id = p_room_id
    returning * into v_room;
  elsif v_room.host_user_id = v_user_id
     or not exists (
       select 1
       from public.room_players
       where room_id = p_room_id
         and user_id = v_room.host_user_id
     ) then
    update public.game_rooms
    set host_user_id = v_next_host
    where id = p_room_id
    returning * into v_room;
  else
    select *
    into v_room
    from public.game_rooms
    where id = p_room_id;
  end if;

  return v_room;
end;
$$;

create or replace function public.heartbeat_game_room(p_room_id uuid)
returns public.game_rooms
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_room public.game_rooms;
begin
  if v_user_id is null then
    raise exception 'You must be logged in.';
  end if;

  update public.room_players
  set last_seen_at = now()
  where room_id = p_room_id
    and user_id = v_user_id;

  if not found then
    raise exception 'You are no longer a member of this room.';
  end if;

  v_room := public.reconcile_game_room_state(p_room_id, 30);
  return v_room;
end;
$$;

create or replace function public.start_game_room(p_room_id uuid)
returns public.game_rooms
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_room public.game_rooms;
begin
  if v_user_id is null then
    raise exception 'You must be logged in.';
  end if;

  update public.room_players
  set last_seen_at = now()
  where room_id = p_room_id
    and user_id = v_user_id;

  v_room := public.reconcile_game_room_state(p_room_id, 30);

  if v_room is null or v_room.status = 'ended' then
    raise exception 'This room has ended.';
  end if;

  update public.game_rooms
  set status = 'playing',
      started_at = coalesce(started_at, now()),
      ended_at = null
  where id = p_room_id
    and host_user_id = v_user_id
    and status = 'waiting'
  returning * into v_room;

  if not found then
    raise exception 'Only the current host can start a waiting room.';
  end if;

  return v_room;
end;
$$;

revoke all on function public.reconcile_game_room_state(uuid, integer) from public, anon, authenticated;
revoke all on function public.create_game_room(text, bigint) from public, anon;
revoke all on function public.join_game_room(text) from public, anon;
revoke all on function public.leave_game_room(uuid) from public, anon;
revoke all on function public.heartbeat_game_room(uuid) from public, anon;
revoke all on function public.start_game_room(uuid) from public, anon;

grant execute on function public.create_game_room(text, bigint) to authenticated;
grant execute on function public.join_game_room(text) to authenticated;
grant execute on function public.leave_game_room(uuid) to authenticated;
grant execute on function public.heartbeat_game_room(uuid) to authenticated;
grant execute on function public.start_game_room(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Realtime lobby updates
-- ---------------------------------------------------------------------------
alter table public.game_rooms replica identity full;
alter table public.room_players replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'game_rooms'
  ) then
    alter publication supabase_realtime add table public.game_rooms;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'room_players'
  ) then
    alter publication supabase_realtime add table public.room_players;
  end if;
end;
$$;
-- P.A.C v7.0 leaderboard upgrade
-- Run this once in Supabase Dashboard -> SQL Editor for an existing project.

alter table public.profiles
  add column if not exists high_score integer not null default 0
  check (high_score >= 0);

create or replace function public.submit_pacman_score(
  p_score integer
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_safe_score integer := greatest(coalesce(p_score, 0), 0);
  v_high_score integer;
begin
  if v_user_id is null then
    raise exception 'You must be logged in to submit a score.';
  end if;

  update public.profiles
  set high_score = greatest(high_score, v_safe_score),
      total_score = total_score + v_safe_score,
      games_played = games_played + 1,
      updated_at = now()
  where id = v_user_id
  returning high_score into v_high_score;

  if v_high_score is null then
    raise exception 'Player profile was not found.';
  end if;

  return v_high_score;
end;
$$;

create or replace function public.get_pacman_high_scores(
  p_limit integer default 10
)
returns table (
  account_name text,
  high_score integer
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    profiles.account_name,
    profiles.high_score
  from public.profiles
  order by
    profiles.high_score desc,
    profiles.account_name asc
  limit greatest(1, least(coalesce(p_limit, 10), 20));
$$;

revoke all on function public.submit_pacman_score(integer) from public;
revoke all on function public.get_pacman_high_scores(integer) from public;

grant execute on function public.submit_pacman_score(integer) to authenticated;
grant execute on function public.get_pacman_high_scores(integer) to anon, authenticated;
